apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-static-website
spec:
  replicas: 2
  selector:
    matchlabels:
      app: kuber-static-website
  template:
    metadata:
      labels:
        app: kuber-static-website
    spec:
      containers:
      - name: kuber-static-website
        image: dhyaneshwari/kuber-static-website:latest
        imagepullpolicy: always
        ports:
        - containerport: 80