apiVersion: v1
kind: Service
metadata:
  name: kuber-static-website-service  # You can rename this
spec:
  selector:
    app: kuber-static-website  # Ensure this matches the label in Deployment YAML
  ports:
    - protocol: TCP
      port: 80  # External port to expose the service
      targetPort: 80  # Ensure this matches the container’s port
      nodePort: 30012  # Choose a node port in the range 30000-32767
  type: NodePort